### ISSUE TITLE
博文中的小错误

### ISSUE THREAD

**Issue by astroHaoPeng** [iamsail/iamsail.github.io#1]
https://www.sail.name/2017/10/02/Multiple-github-count-in-one-system/
中
`git@github.com:test/Mywork.git，替换后应该是：github2:test/Mywork.git.`
这一行，少写了`git@`

是吗？

**Comment by iamsail** [comment]
不是的，这里没有少写。就是替换了一个别名，将 git@github.com 替换成了github2

**Comment by iamsail** [comment]
@astroHaoPeng  不是的，这里没有少写。就是替换了一个别名，将 git@github.com 替换成了github2
